export const prebuiltCards = [
    // Alphabet & Simple Words
    { front: "Apple", back: "A sweet, crunchy red or green fruit." },
    { front: "Bear", back: "A large, furry wild animal." },
    { front: "Cat", back: "A small furry pet that purrs." },
    { front: "Dog", back: "A friendly pet that barks." },
    { front: "Elephant", back: "A huge animal with a long trunk." },
    { front: "Frog", back: "A small green animal that jumps." },
    { front: "Goat", back: "A farm animal with horns." },
    { front: "Hat", back: "Something you wear on your head." },
    { front: "Ice", back: "Frozen water." },
    { front: "Jump", back: "To push yourself up into the air." },
    { front: "Kite", back: "A toy that flies in the wind." },
    { front: "Lion", back: "A large, wild cat with a mane." },
    { front: "Moon", back: "The large white circle in the night sky." },
    { front: "Nest", back: "A home made by a bird." },
    { front: "Owl", back: "A bird that stays awake at night." },
    { front: "Pig", back: "A pink farm animal with a curly tail." },
    { front: "Queen", back: "A woman who rules a country." },
    { front: "Rabbit", back: "A small animal with long ears." },
    { front: "Sun", back: "The bright star that gives us daylight." },
    { front: "Tree", back: "A tall plant with a wooden trunk and leaves." },
    { front: "Umbrella", back: "Used to keep you dry in the rain." },
    { front: "Van", back: "A large vehicle used for moving things." },
    { front: "Water", back: "A clear liquid we drink to stay alive." },
    { front: "X-ray", back: "A picture that shows the bones inside your body." },
    { front: "Yellow", back: "The color of the sun and lemons." },
    { front: "Zebra", back: "A wild horse with black and white stripes." },

    // Sight Words
    { front: "The", back: "Used to point to a specific thing." },
    { front: "And", back: "Used to join words together." },
    { front: "You", back: "The person I am talking to." },
    { front: "That", back: "Used to point to something far away." },
    { front: "It", back: "Used to talk about a thing or animal." },
    { front: "He", back: "Used to talk about a boy or man." },
    { front: "Was", back: "Used to talk about something in the past." },
    { front: "For", back: "Used to show who gets something." },
    { front: "On", back: "Touching the top of something." },
    { front: "Are", back: "Used to talk about more than one person or thing." },
    { front: "With", back: "Being together or using something." },
    { front: "His", back: "Belonging to a boy or man." },
    { front: "They", back: "Used to talk about a group of people." },
    { front: "I", back: "Used when talking about yourself." },
    { front: "At", back: "Showing where someone or something is." },
    { front: "Be", back: "To exist or live." },
    { front: "This", back: "Used to point to something close." },
    { front: "Have", back: "To own or hold something." },
    { front: "From", back: "Showing where something started." },
    { front: "Or", back: "Used to show a choice." },
    { front: "One", back: "The number 1." },
    { front: "Had", back: "Owned something in the past." },
    { front: "By", back: "Next to or near." },
    { front: "Word", back: "Letters put together that mean something." },

    // Colors & Shapes
    { front: "Red", back: "The color of an apple or a stop sign." },
    { front: "Blue", back: "The color of the clear sky." },
    { front: "Green", back: "The color of grass and leaves." },
    { front: "Orange", back: "A color made by mixing red and yellow." },
    { front: "Purple", back: "A color made by mixing red and blue." },
    { front: "Black", back: "The color of the night sky." },
    { front: "White", back: "The color of snow." },
    { front: "Circle", back: "A perfectly round shape." },
    { front: "Square", back: "A shape with four equal sides." },
    { front: "Triangle", back: "A shape with three sides." },

    // Nature & Science
    { front: "Star", back: "A bright dot in the night sky." },
    { front: "Planet", back: "A large, round rock or ball of gas in space." },
    { front: "Galaxy", back: "A huge group of stars and planets." },
    { front: "Astronaut", back: "A person who travels to space." },
    { front: "Ocean", back: "A very large body of salt water." },
    { front: "Mountain", back: "A very tall piece of land." },
    { front: "River", back: "A moving stream of water." },
    { front: "Cloud", back: "A white or gray puff in the sky made of water drops." },
    { front: "Rain", back: "Water that falls from the clouds." },
    { front: "Snow", back: "Soft, white frozen rain." },
    { front: "Wind", back: "Moving air." },
    { front: "Fire", back: "Burning wood or gas that gives off heat and light." },
    { front: "Earth", back: "The planet we live on." },
    { front: "Space", back: "The empty area past Earth's sky." },
    { front: "Gravity", back: "The force that pulls things down to the ground." },
    { front: "Magnet", back: "A piece of metal that pulls other metal towards it." },
    { front: "Energy", back: "Power that makes things move or light up." },
    { front: "Plant", back: "A living thing with leaves and roots." },
    { front: "Seed", back: "A tiny part of a plant that can grow into a new plant." },
    { front: "Root", back: "The part of a plant that grows underground." },

    // Daily Life
    { front: "House", back: "A building where people live." },
    { front: "School", back: "A place where children go to learn." },
    { front: "Book", back: "Pages with words and pictures that you read." },
    { front: "Pencil", back: "A tool used for writing or drawing." },
    { front: "Chair", back: "A piece of furniture you sit on." },
    { front: "Table", back: "A piece of furniture with a flat top and legs." },
    { front: "Bed", back: "A place where you sleep." },
    { front: "Clock", back: "A tool used to tell the time." },
    { front: "Phone", back: "A device used to talk to people far away." },
    { front: "Computer", back: "A machine used for learning, working, and playing." },
    { front: "Car", back: "A vehicle with four wheels used to travel." },
    { front: "Bus", back: "A large vehicle that carries many people." },
    { front: "Train", back: "A long vehicle that runs on metal tracks." },
    { front: "Airplane", back: "A flying vehicle with wings." },
    { front: "Boat", back: "A vehicle that travels on water." },
    { front: "Road", back: "A hard path for cars to drive on." },
    { front: "Bridge", back: "A path built over water or a valley." },
    { front: "Shoe", back: "Something you wear on your foot." },
    { front: "Shirt", back: "Clothing worn on the top part of your body." },
    { front: "Pants", back: "Clothing worn on your legs." }
];
